server:
  port: 8080
  servlet:
      context-path: /
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.chat.qs.entity
spring:
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/qs?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    encoding:
      force: true
      charset: UTF-8
  application:
      name: chat-netty-websocket
#  data:
#    elasticsearch:
#      #节点地址，多个节点用逗号隔开
#      #默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
#      cluster-nodes: 127.0.0.1:9300
#      cluster-name: elasticsearch-cluster #节点名字，默认elasticsearch
#      local: true #开启 Elasticsearch 仓库(默认值:true)
#      repositories:
#        enabled: true #仓库中存储数据
#      properties:
#        transport:
#          tcp:
#            connect_timeout: 120s
#        path:
#          home: /data/project/target/elastic
#          logs: /data/project/target/elastic
#          data: /data/project/target/elastic
logging:
  level:
    com.chat.qs.mapper: debug
